name: Greeting from CHOI_CHUNG_YU
on: push

jobs:

 my-job:
  name: My Job
  runs-on: ubuntu-latest
  steps:
  - name: Print a greeting
    env:
      MY_VAR: Hi there! My name is
      FIRST_NAME: CHOI
      MIDDLE_NAME: CHUNG
      LAST_NAME: YU
    run: |
     echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
